{ 
  "hostid": "007f0101",
  "hostname": "atom",
  "ostype": "ubuntu",
  "osver": "14.10",
  "arch": "amd64",
  "check": "loadaverage",
  "params": "None",
  "result": {
    "1": 0.4,
    "5": 4.5,
    "15": 3.4
  }
}

{
  "hostid": "007f0101",
  "hostname": "atom",
  "ostype": "ubuntu",
  "osver": "14.10",
  "arch": "amd64",
  "check": "diskspace",
  "params": "None" ,
  "result": {
    "/": {
      "capacity": 5000,
      "free": 4000
    },
    "/home": {
      "capacity": 50000,
      "free": 40000
    }
  }
}
